$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: iitb-nmt--t4--gpu
endpoint_name: iitb-nmt--t4
model: azureml:nmt--iitb--models:1
model_mount_path: /models
environment: azureml:triton-nmt-monolingual-env:1
instance_type: Standard_NC4as_T4_v3
instance_count: 1
request_settings:
  request_timeout_ms: 90000
  max_concurrent_requests_per_instance: 128
  max_queue_wait_ms: 1000
app_insights_enabled: true
